version: "2"

services:

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/etc:/fluentd/etc
    depends_on: 
      - elasticsearch  
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"       
    restart: always

  kibana:
    image: kibana    
    ports:
      - "5601:5601"  
    links:
      - elasticsearch

  nginx:
    build: ./poc-microservice-frontend
    ports:
      - "80:80"
    logging:
      driver: fluentd
    links:
      - elasticsearch
    depends_on: 
      - fluentd  
    restart: always

  restapi:
    build: ./poc-restify
    ports:
      - "8000:8000"
    logging:
      driver: fluentd  
    links:
      - fluentd
    depends_on: 
      - fluentd      